version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@7

aliases:
  - &node_image cimg/node:16.20.2

jobs:
  build:
    docker:
      - image: *node_image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Unit Tests
          command: npm test
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish

workflows:
  build:
    jobs:
      - build:
          context: 6rs-public-npm
